services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: stock
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stock
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "4200:4200"
        depends_on:
            - backend
        networks:
            - app-network

volumes:
    postgres_data:

networks:
    app-network:
